### ISSUE TITLE
yo yo yo

### ISSUE THREAD

**Issue by zghwi** [elipie/DragonLang#1]
WHAT LANGUAGE ARE YOU GOING TO USE TO BUILD THIS LANGUAGE ~~OFC C++ LIKE PIELANG TWT~~?

**Comment by zghwi** [comment]
i didn't read the readme im dumb its written in c bruh smh twt

**Comment by elipie** [comment]
lol

**Comment by firefish111** [comment]
lmao

**Comment by firefish111** [comment]
g
